/*
 * generated by Xtext 2.21.0
 */
package org.virtio.virtiodriver.ftracelanguage.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.virtio.virtiodriver.ftracelanguage.ui.internal.FtracelanguageActivator;

public class FrtraceLanguageUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return FtracelanguageActivator.getInstance().getInjector("org.virtio.virtiodriver.ftracelanguage.FrtraceLanguage");
	}

}
