/*
 * generated by Xtext 2.21.0
 */
package org.virtio.virtiodriver.ftracelanguage.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FrtraceLanguageUiModule extends AbstractFrtraceLanguageUiModule {

	public FrtraceLanguageUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
