/*
 * generated by Xtext 2.21.0
 */
package org.virtio.virtiodriver.ftracelanguage.ide;


/**
 * Use this class to register ide components.
 */
public class FrtraceLanguageIdeModule extends AbstractFrtraceLanguageIdeModule {
}
