/*
 * generated by Xtext 2.21.0
 */
package org.virtio.virtiodriver.ftracelanguage.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.virtio.virtiodriver.ftracelanguage.FrtraceLanguageRuntimeModule;
import org.virtio.virtiodriver.ftracelanguage.FrtraceLanguageStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FrtraceLanguageIdeSetup extends FrtraceLanguageStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FrtraceLanguageRuntimeModule(), new FrtraceLanguageIdeModule()));
	}
	
}
