/*
 * generated by Xtext 2.21.0
 */
package org.virtio.virtiodriver.ftracelanguage.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.virtio.virtiodriver.ftracelanguage.parser.antlr.internal.InternalFrtraceLanguageParser;
import org.virtio.virtiodriver.ftracelanguage.services.FrtraceLanguageGrammarAccess;

public class FrtraceLanguageParser extends AbstractAntlrParser {

	@Inject
	private FrtraceLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFrtraceLanguageParser createParser(XtextTokenStream stream) {
		return new InternalFrtraceLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "TraceModel";
	}

	public FrtraceLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FrtraceLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
