/*
 * generated by Xtext 2.21.0
 */
package org.virtio.virtiodriver.ftracelanguage;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class FrtraceLanguageRuntimeModule extends AbstractFrtraceLanguageRuntimeModule {
}
