/**
 * generated by Xtext 2.21.0
 */
package org.virtio.virtiodriver.ftracelanguage.frtraceLanguage;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.FrtraceLanguageFactory
 * @model kind="package"
 * @generated
 */
public interface FrtraceLanguagePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "frtraceLanguage";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.virtio.org/virtiodriver/ftracelanguage/FrtraceLanguage";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "frtraceLanguage";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  FrtraceLanguagePackage eINSTANCE = org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.FrtraceLanguagePackageImpl.init();

  /**
   * The meta object id for the '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.TraceModelImpl <em>Trace Model</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.TraceModelImpl
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.FrtraceLanguagePackageImpl#getTraceModel()
   * @generated
   */
  int TRACE_MODEL = 0;

  /**
   * The feature id for the '<em><b>Traces</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACE_MODEL__TRACES = 0;

  /**
   * The number of structural features of the '<em>Trace Model</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACE_MODEL_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.TraceImpl <em>Trace</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.TraceImpl
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.FrtraceLanguagePackageImpl#getTrace()
   * @generated
   */
  int TRACE = 1;

  /**
   * The feature id for the '<em><b>First</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACE__FIRST = 0;

  /**
   * The feature id for the '<em><b>Second</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACE__SECOND = 1;

  /**
   * The feature id for the '<em><b>Timestamp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACE__TIMESTAMP = 2;

  /**
   * The feature id for the '<em><b>Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACE__DEC = 3;

  /**
   * The feature id for the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACE__FUNCTION = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACE__NAME = 5;

  /**
   * The number of structural features of the '<em>Trace</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRACE_FEATURE_COUNT = 6;


  /**
   * Returns the meta object for class '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.TraceModel <em>Trace Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trace Model</em>'.
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.TraceModel
   * @generated
   */
  EClass getTraceModel();

  /**
   * Returns the meta object for the containment reference list '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.TraceModel#getTraces <em>Traces</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Traces</em>'.
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.TraceModel#getTraces()
   * @see #getTraceModel()
   * @generated
   */
  EReference getTraceModel_Traces();

  /**
   * Returns the meta object for class '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace <em>Trace</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Trace</em>'.
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace
   * @generated
   */
  EClass getTrace();

  /**
   * Returns the meta object for the attribute '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getFirst <em>First</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>First</em>'.
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getFirst()
   * @see #getTrace()
   * @generated
   */
  EAttribute getTrace_First();

  /**
   * Returns the meta object for the attribute '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getSecond <em>Second</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Second</em>'.
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getSecond()
   * @see #getTrace()
   * @generated
   */
  EAttribute getTrace_Second();

  /**
   * Returns the meta object for the attribute '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getTimestamp <em>Timestamp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Timestamp</em>'.
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getTimestamp()
   * @see #getTrace()
   * @generated
   */
  EAttribute getTrace_Timestamp();

  /**
   * Returns the meta object for the attribute '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getDec <em>Dec</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Dec</em>'.
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getDec()
   * @see #getTrace()
   * @generated
   */
  EAttribute getTrace_Dec();

  /**
   * Returns the meta object for the attribute '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getFunction <em>Function</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Function</em>'.
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getFunction()
   * @see #getTrace()
   * @generated
   */
  EAttribute getTrace_Function();

  /**
   * Returns the meta object for the attribute '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getName()
   * @see #getTrace()
   * @generated
   */
  EAttribute getTrace_Name();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  FrtraceLanguageFactory getFrtraceLanguageFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.TraceModelImpl <em>Trace Model</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.TraceModelImpl
     * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.FrtraceLanguagePackageImpl#getTraceModel()
     * @generated
     */
    EClass TRACE_MODEL = eINSTANCE.getTraceModel();

    /**
     * The meta object literal for the '<em><b>Traces</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRACE_MODEL__TRACES = eINSTANCE.getTraceModel_Traces();

    /**
     * The meta object literal for the '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.TraceImpl <em>Trace</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.TraceImpl
     * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.impl.FrtraceLanguagePackageImpl#getTrace()
     * @generated
     */
    EClass TRACE = eINSTANCE.getTrace();

    /**
     * The meta object literal for the '<em><b>First</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRACE__FIRST = eINSTANCE.getTrace_First();

    /**
     * The meta object literal for the '<em><b>Second</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRACE__SECOND = eINSTANCE.getTrace_Second();

    /**
     * The meta object literal for the '<em><b>Timestamp</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRACE__TIMESTAMP = eINSTANCE.getTrace_Timestamp();

    /**
     * The meta object literal for the '<em><b>Dec</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRACE__DEC = eINSTANCE.getTrace_Dec();

    /**
     * The meta object literal for the '<em><b>Function</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRACE__FUNCTION = eINSTANCE.getTrace_Function();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRACE__NAME = eINSTANCE.getTrace_Name();

  }

} //FrtraceLanguagePackage
