/**
 * generated by Xtext 2.21.0
 */
package org.virtio.virtiodriver.ftracelanguage.frtraceLanguage;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trace Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.TraceModel#getTraces <em>Traces</em>}</li>
 * </ul>
 *
 * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.FrtraceLanguagePackage#getTraceModel()
 * @model
 * @generated
 */
public interface TraceModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Traces</b></em>' containment reference list.
   * The list contents are of type {@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Traces</em>' containment reference list.
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.FrtraceLanguagePackage#getTraceModel_Traces()
   * @model containment="true"
   * @generated
   */
  EList<Trace> getTraces();

} // TraceModel
