/**
 * generated by Xtext 2.21.0
 */
package org.virtio.virtiodriver.ftracelanguage.frtraceLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trace</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getFirst <em>First</em>}</li>
 *   <li>{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getSecond <em>Second</em>}</li>
 *   <li>{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getTimestamp <em>Timestamp</em>}</li>
 *   <li>{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getDec <em>Dec</em>}</li>
 *   <li>{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getFunction <em>Function</em>}</li>
 *   <li>{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.FrtraceLanguagePackage#getTrace()
 * @model
 * @generated
 */
public interface Trace extends EObject
{
  /**
   * Returns the value of the '<em><b>First</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First</em>' attribute.
   * @see #setFirst(String)
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.FrtraceLanguagePackage#getTrace_First()
   * @model
   * @generated
   */
  String getFirst();

  /**
   * Sets the value of the '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getFirst <em>First</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First</em>' attribute.
   * @see #getFirst()
   * @generated
   */
  void setFirst(String value);

  /**
   * Returns the value of the '<em><b>Second</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Second</em>' attribute.
   * @see #setSecond(int)
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.FrtraceLanguagePackage#getTrace_Second()
   * @model
   * @generated
   */
  int getSecond();

  /**
   * Sets the value of the '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getSecond <em>Second</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Second</em>' attribute.
   * @see #getSecond()
   * @generated
   */
  void setSecond(int value);

  /**
   * Returns the value of the '<em><b>Timestamp</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Timestamp</em>' attribute.
   * @see #setTimestamp(int)
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.FrtraceLanguagePackage#getTrace_Timestamp()
   * @model
   * @generated
   */
  int getTimestamp();

  /**
   * Sets the value of the '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getTimestamp <em>Timestamp</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Timestamp</em>' attribute.
   * @see #getTimestamp()
   * @generated
   */
  void setTimestamp(int value);

  /**
   * Returns the value of the '<em><b>Dec</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dec</em>' attribute.
   * @see #setDec(int)
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.FrtraceLanguagePackage#getTrace_Dec()
   * @model
   * @generated
   */
  int getDec();

  /**
   * Sets the value of the '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getDec <em>Dec</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dec</em>' attribute.
   * @see #getDec()
   * @generated
   */
  void setDec(int value);

  /**
   * Returns the value of the '<em><b>Function</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' attribute.
   * @see #setFunction(String)
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.FrtraceLanguagePackage#getTrace_Function()
   * @model
   * @generated
   */
  String getFunction();

  /**
   * Sets the value of the '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getFunction <em>Function</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' attribute.
   * @see #getFunction()
   * @generated
   */
  void setFunction(String value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.FrtraceLanguagePackage#getTrace_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.virtio.virtiodriver.ftracelanguage.frtraceLanguage.Trace#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

} // Trace
